server:
  port: 7071
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  feign.client.url.TestUrl: http://localhost:8093
  
